# creaet a  contaienr using mysql:lts 
# usr root, password password, database mydb
# expose port 3306


# creat a redis container 


#create a RabbitMQ container

version: '3'
services:
  mysql:
    image: mysql:lts
    environment:
      MYSQL_ROOT_PASSWORD: password
    expose:
      - "3306"
    volumes:
      - mysql-data:/var/lib/mysql
  redis:
    image: redis
    expose:
      - "6379"
    environment:
      - REDIS_PASSWORD=password
    volumes:
      - redis-data:/data
  rabbitmq:
    image: rabbitmq:3-management
    expose:
      - "5672"
    ports:
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
  vhr-backend:
    image: ${DOCKER_REGISTRY}/${DOCKER_IMAGE}:${VHRBACKEND_VERSION}
    expose:
      - "8081" 
    depends_on:
      - mysql
      - redis
      - rabbitmq
    environment:
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - DB_HOSTNAME=mysql
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_HOST=rabbitmq
      - REDIS_HOST=redis
      - REDIS_PASSWORD=password


  vhr-ui:
    image: vhr-ui:1.0
    ports:
      - "80:80"
    depends_on:
      - vhr-backend
    volumes:
      - ./vuehr/nginx.conf:/etc/nginx/conf.d/default.conf
    

    
volumes:
  mysql-data:
  redis-data:
  rabbitmq-data:

