apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUREekNDQWZlZ0F3SUJBZ0lVREg3RTc5bzBCQzExcWJpcDZ6Vi9Lakc3UHlnd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0Z6RVZNQk1HQTFVRUF3d01NVEF1TVRVeUxqRTRNeTR4TUI0WERUSTFNRFF4TlRBNU1UVTBORm9YRFRNMQpNRFF4TXpBNU1UVTBORm93RnpFVk1CTUdBMVVFQXd3TU1UQXVNVFV5TGpFNE15NHhNSUlCSWpBTkJna3Foa2lHCjl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF4VG5FQ1RjMkFTQks4WVFOOUszai9USHJuTjFLYVpYNmpPelYKTnFja1ozUUQyYjVpQjA0djZ6OHV0OEsrd250am5ZM1lhcTRQR3Y1MTVFYTR6VGFGY3MvTG5nV1dObkpkaWpwYQpmZitVK1hMZHVJYUV2T0JoMUdXb1VHYXVuOHBXRlNMb0F6WHh0RFJiSzd6RXhHQ0FJYXIzbkRwVmQveGNTMmVnCmM2K2llZERMMTBPTkd2SzNyZmppTUxJUEtNQVZiZzU0dUtHQkpCN295N3Y3bkdkTWVvcTZKMGVGak1QYXZWcHMKQ2VONHJNL2ZiTDJTQ3d5SVlKL3NtaGNHMVYxK2lNemU0RVVocm5hTFBFVVJFdnJVWE5NU1Z3RVBCN0ZWL0g1bwo3U2w2Nkdlb3dQZ2FlYTczQkxheXJMVVBzeFFrKzUvcTBwWDQzaGJjMUUxVitQQWVMUUlEQVFBQm8xTXdVVEFkCkJnTlZIUTRFRmdRVWNSNTJWUTQ1R01HV2MvQXRjdjlMcnJiOWVwa3dId1lEVlIwakJCZ3dGb0FVY1I1MlZRNDUKR01HV2MvQXRjdjlMcnJiOWVwa3dEd1lEVlIwVEFRSC9CQVV3QXdFQi96QU5CZ2txaGtpRzl3MEJBUXNGQUFPQwpBUUVBYTZqQ1Q5b1VXdmVGaVE1MGpFdUlueTgwN0h4NUdLQ0VQa250MCtWcXhRb0VKTERPRVo3QlQ3VVdMcTBCClc5Y1dHVHNneVZmekY5NmU5Y3dIOWgvYk5TUUkva2M2aUx0dlN1N3hGMDBqMDF3N3E4OHg0YWVrRytQTVczQVUKU3hOc1cxTm9qdUVjVG9YMk0ySmNKbGIxaExTZXp0aG9iMytKQ0h3WjIxaGw0OXBlTFFqSlRBNlAvZmorazBwOQpKZXJRN3ErRWl3RFV0YnE4NjV3N1NST2Z2Uno3cS9JL1VNMHdYc2tRaWpNcnZrY3BxK3ZkRmpTdDR6a0hRRXdSCnZqV1AzVi85Q3JHMU1ZaG1rTzdTcTY2MTh4Z2Iyd2EvOVk5UnRTQlNaVjFJbFQ5U254eEc2ZkRzY3l3SXZuR0cKbnBrV2RIdGlIbTk1dDJPVTkxOXRsTHNWc0E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://172.31.59.89:16443
  name: microk8s-cluster
contexts:
- context:
    cluster: microk8s-cluster
    user: admin
  name: microk8s
current-context: microk8s
kind: Config
preferences: {}
users:
- name: admin
  user:
    token: cUVpRTI3R3NLbGV6QUg3ZHg0d1RiREM0VkFJK1o5aytQSUkrSzczS3NLZz0K

