apiVersion: v1
kind: Secret
metadata:
  name: vhr-secrets
  namespace: {{ .Release.Namespace }}  # Use the same namespace as the deployment
type: Opaque
data:
  {{- $secretFile := .Files.Get ".secret" | fromYaml }}
  {{- range $key, $value := $secretFile }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}